/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Backend {
  /**
   * `app_data_dir` は Electron main の `app.getPath("userData")` を明示注入
   * (§4.2 / §6.8 — Phase 2 は `GrimodexElectronDev` 名で動かし、Tauri の
   * com.miyakey.grimodex には触らない)。
   */
  constructor(appDataDir: string)
  /**
   * drizzle-proxy (src/db/client.ts) の唯一の通り道 (§4.3 — これだけで
   * CRUD の 9 割が生きる)。`params` は位置パラメータの JSON 配列、`method`
   * は "run" | "get" | "all" | "values"。
   * 返り値: `QueryResult` の JSON 文字列 `{"rows":[…]}` (Tauri ワイヤと同形)。
   */
  dbExecute(sql: string, params: any, method: string): Promise<string>
  /**
   * 複数文を単一トランザクションで実行 (BEGIN IMMEDIATE、途中失敗で全
   * ROLLBACK — grimodex-db の `execute_batch_tx`)。オートセーブの通り道。
   * `statements` は `[{ sql, params, method }, …]`。
   * 返り値: 最終文の rows を載せた `QueryResult` の JSON 文字列。
   */
  dbExecuteBatch(statements: any): Promise<string>
  /**
   * workspace を開く: backup → migrate → swap → RAII SwitchingGuard →
   * recent-workspaces 更新 (`grimodex_db::open::open_workspace_sync` —
   * Tauri コマンドと同一経路。A3 相互運用の根拠)。`on_swapped` は napi 側
   * no-op (semantic キャッシュは Tauri シェル固有。§4.1)。
   * 完了時に `workspace:opened` (FE 購読者なしのデバッグチャネル) を emit
   * する (§7.1 の end-to-end 実証チャネルその 2)。
   * 返り値: `{"name":…,"isExisting":…}` の JSON 文字列。
   */
  openWorkspace(path: string): Promise<string>
  /**
   * 既存 workspace 判定 (commands/workspace.rs の同名コマンドと同一実装)。
   * 軽量 stat のみなので設計どおり同期のまま (§4.2「純関数の validate 除く」)。
   */
  validateWorkspacePath(path: string): boolean
  /**
   * 起動時に必ず呼ばれる (workspace/store.ts:152)。
   * 返り値: `GlobalSettings` の JSON 文字列 (camelCase — Tauri ワイヤと同形)。
   */
  getGlobalSettings(): Promise<string>
  /**
   * `settings` は GlobalSettings 全体 (camelCase オブジェクト)。tmp+rename の
   * 原子的書き込みと write_lock 直列化は Tauri コマンドと同一経路。
   */
  saveGlobalSettings(settings: any): Promise<void>
  /**
   * 監査チェーン append (commands/timelapse.rs の写像。編集ループ常連の
   * 軽量 DB 書き込み。§4.3)。`events` は camelCase の AppendChangeEvent 配列
   * (Tauri の camelCase→snake_case 自動変換は serde の rename_all が担う)。
   * 返り値: `AppendResult` (`{"insertedCount":…,"tailSequence":…,"tailHash":…}`)
   * の JSON 文字列。
   */
  timelapseAppendBatch(projectId: string, sessionId: string, events: any): Promise<string>
  /**
   * main 起動時に 1 回登録する (§7.1)。コールバックは
   * `(channel: string, payloadJson: string)` の 2 引数。登録前に emit された
   * イベント (`backend:ready`) は登録時に emit 順で flush される。
   * TSFn は unref 済み — 登録が Node のイベントループを生かし続けることは
   * ない (プロセス終了を妨げない)。
   */
  onEvent(callback: (...args: any[]) => any): void
}
