/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Backend {
  /**
   * `app_data_dir` は Electron main の `app.getPath("userData")` を明示注入
   * (§4.2 / §6.8 — Phase 2 は `GrimodexElectronDev` 名で動かし、Tauri の
   * com.miyakey.grimodex には触らない)。
   */
  constructor(appDataDir: string)
  /**
   * drizzle-proxy (src/db/client.ts) の唯一の通り道 (§4.3 — これだけで
   * CRUD の 9 割が生きる)。`params` は位置パラメータの JSON 配列、`method`
   * は "run" | "get" | "all" | "values"。
   * 返り値: `QueryResult` の JSON 文字列 `{"rows":[…]}` (Tauri ワイヤと同形)。
   */
  dbExecute(sql: string, params: any, method: string): Promise<string>
  /**
   * 複数文を単一トランザクションで実行 (BEGIN IMMEDIATE、途中失敗で全
   * ROLLBACK — grimodex-db の `execute_batch_tx`)。オートセーブの通り道。
   * `statements` は `[{ sql, params, method }, …]`。
   * 返り値: 最終文の rows を載せた `QueryResult` の JSON 文字列。
   */
  dbExecuteBatch(statements: any): Promise<string>
  /**
   * workspace を開く: backup → migrate → swap → RAII SwitchingGuard →
   * recent-workspaces 更新 (`grimodex_db::open::open_workspace_sync` —
   * Tauri コマンドと同一経路。A3 相互運用の根拠)。`on_swapped` は napi 側
   * no-op (semantic キャッシュは Tauri シェル固有。§4.1)。
   * 完了時に `workspace:opened` (FE 購読者なしのデバッグチャネル) を emit
   * する (§7.1 の end-to-end 実証チャネルその 2)。
   * 返り値: `{"name":…,"isExisting":…}` の JSON 文字列。
   */
  openWorkspace(path: string): Promise<string>
  /**
   * 既存 workspace 判定 (commands/workspace.rs の同名コマンドと同一実装)。
   * 軽量 stat のみなので設計どおり同期のまま (§4.2「純関数の validate 除く」)。
   */
  validateWorkspacePath(path: string): boolean
  /**
   * 起動時に必ず呼ばれる (workspace/store.ts:152)。
   * 返り値: `GlobalSettings` の JSON 文字列 (camelCase — Tauri ワイヤと同形)。
   */
  getGlobalSettings(): Promise<string>
  /**
   * `settings` は GlobalSettings 全体 (camelCase オブジェクト)。tmp+rename の
   * 原子的書き込みと write_lock 直列化は Tauri コマンドと同一経路。
   */
  saveGlobalSettings(settings: any): Promise<void>
  /**
   * 監査チェーン append (commands/timelapse.rs の写像。編集ループ常連の
   * 軽量 DB 書き込み。§4.3)。`events` は camelCase の AppendChangeEvent 配列
   * (Tauri の camelCase→snake_case 自動変換は serde の rename_all が担う)。
   * 返り値: `AppendResult` (`{"insertedCount":…,"tailSequence":…,"tailHash":…}`)
   * の JSON 文字列。
   */
  timelapseAppendBatch(projectId: string, sessionId: string, events: any): Promise<string>
  /**
   * 文字屑ゴミ箱: 作成 (commands/trash_bin.rs の写像 — 実装本体は
   * `grimodex_db::trash_bin` を Tauri コマンドと共用)。trash_bin 5 コマンドは
   * workspace 読み込み時に `trash_bin_list` が必ず呼ばれるため、垂直スライスに
   * 含めないと Electron 起動のたびにゴミ箱エラートーストが出る (§4.3)。
   * `payload` は camelCase の TrashBinCreatePayload。
   * 返り値: 作成行 (`SELECT *`、列名は snake_case) の JSON 文字列。
   */
  trashBinCreate(payload: any): Promise<string>
  /**
   * 文字屑ゴミ箱: 一覧 (deleted_at 降順、`limit` 省略時 50 件)。
   * 返り値: 行オブジェクト配列の JSON 文字列。
   */
  trashBinList(projectId: string, limit?: number | undefined | null): Promise<string>
  /** 文字屑ゴミ箱: 1 件削除 (拾い上げ成功時にも呼ばれる)。 */
  trashBinDelete(id: string): Promise<void>
  /** 文字屑ゴミ箱: project 内全削除。 */
  trashBinClearAll(projectId: string): Promise<void>
  /**
   * 文字屑ゴミ箱: 期日切れ・件数超過の刈り取り (起動時に呼ばれる)。
   * 返り値: 残件数 (i64) の JSON 文字列。
   */
  trashBinPrune(projectId: string, retentionDays: number, maxCount: number): Promise<string>
  /**
   * FTS optimize (commands/integrity.rs の写像 — 実装は grimodex-db の
   * `Database::fts_optimize` を Tauri と共用)。workspace open 後のアイドル
   * タイミングで呼ばれる fail-soft コマンド。
   */
  ftsOptimize(): Promise<void>
  /** FTS 全再構築 (設定画面のデータカテゴリから明示実行)。 */
  ftsRebuild(): Promise<void>
  /** 英語 FTS の再構築 (英語プロジェクト作成時に fail-soft で呼ばれる)。 */
  ftsRebuildEn(): Promise<void>
  /**
   * FTS 検索 (チャット recall / コマンドセンター検索 — 編集ループ常連)。
   * 返り値: 行オブジェクト配列の JSON 文字列。
   */
  ftsSearch(projectId: string, query: string, scope: string, limit: number): Promise<string>
  /**
   * 整合性チェック (IntegrityCheckDialog)。
   * 返り値: レポート object の JSON 文字列。
   */
  integrityCheck(): Promise<string>
  /**
   * 整合性修復 (IntegrityCheckDialog — 長時間になりうるが spawn_blocking
   * なので Node main thread は塞がない)。
   * 返り値: レポート object の JSON 文字列。
   */
  repairIntegrity(): Promise<string>
  /**
   * Linter 本体 (commands/lint.rs の写像 — grimodex-lint を Tauri と共用)。
   * State 非依存だが、UniDic コールドロード (初回 >数秒) + CPU バウンドなので
   * spawn_blocking。エラーは AppError ではなく **LintError の {type,data}
   * JSON** を reason に載せる (convert::lint_err_to_napi — ipcContract の
   * lint_text アダプタが object reject へ復元する)。
   * 返り値: `LintResponse` の JSON 文字列。
   */
  lintText(blocks: any, language: string, scope: any, config: any, disables?: any | undefined | null): Promise<string>
  /**
   * 段落プレーンテキストの文節分割 (commands/reorder.rs の写像)。
   * UniDic コールドロードで初回 10s 超えうる (FE 側 SLOW_COMMANDS 登録済み)。
   * 返り値: `[{start, end, surface}, …]` (UTF-16 offset) の JSON 文字列。
   */
  segmentBunsetsu(text: string): Promise<string>
  /**
   * システムフォント列挙 (commands/fonts.rs の写像 — 実装本体は
   * grimodex-fonts を Tauri と共用)。OS のフォントディレクトリスキャンは
   * 数百 ms かかりうるため spawn_blocking。
   * 返り値: family 名配列 (昇順・重複排除) の JSON 文字列。
   */
  listSystemFonts(): Promise<string>
  /**
   * main 起動時に 1 回登録する (§7.1)。コールバックは
   * `(channel: string, payloadJson: string)` の 2 引数。登録前に emit された
   * イベント (`backend:ready`) は登録時に emit 順で flush される。
   * TSFn は unref 済み — 登録が Node のイベントループを生かし続けることは
   * ない (プロセス終了を妨げない)。
   */
  onEvent(callback: (...args: any[]) => any): void
}
