export interface ThemePalette {
  "--background": string;
  "--foreground": string;
  "--card": string;
  "--card-foreground": string;
  "--popover": string;
  "--popover-foreground": string;
  "--primary": string;
  "--primary-foreground": string;
  "--secondary": string;
  "--secondary-foreground": string;
  "--muted": string;
  "--muted-foreground": string;
  "--accent": string;
  "--accent-foreground": string;
  "--destructive": string;
  "--destructive-foreground": string;
  "--border": string;
  "--input": string;
  "--ring": string;
  "--sidebar-background": string;
  "--sidebar-foreground": string;
  "--sidebar-primary": string;
  "--sidebar-primary-foreground": string;
  "--sidebar-accent": string;
  "--sidebar-accent-foreground": string;
  "--sidebar-border": string;
  "--sidebar-ring": string;
}

export interface ColorTheme {
  id: string;
  name: string;
  light: ThemePalette;
  dark: ThemePalette;
}

// CSS variable names that themes override
export const THEME_CSS_VARS = [
  "--background",
  "--foreground",
  "--card",
  "--card-foreground",
  "--popover",
  "--popover-foreground",
  "--primary",
  "--primary-foreground",
  "--secondary",
  "--secondary-foreground",
  "--muted",
  "--muted-foreground",
  "--accent",
  "--accent-foreground",
  "--destructive",
  "--destructive-foreground",
  "--border",
  "--input",
  "--ring",
  "--sidebar-background",
  "--sidebar-foreground",
  "--sidebar-primary",
  "--sidebar-primary-foreground",
  "--sidebar-accent",
  "--sidebar-accent-foreground",
  "--sidebar-border",
  "--sidebar-ring",
] as const;

export const COLOR_THEMES: ColorTheme[] = [
  {
    id: "simple",
    name: "Simple",
    light: {
      "--background": "oklch(1 0 0)",
      "--foreground": "oklch(0.145 0 0)",
      "--card": "oklch(1 0 0)",
      "--card-foreground": "oklch(0.145 0 0)",
      "--popover": "oklch(1 0 0)",
      "--popover-foreground": "oklch(0.145 0 0)",
      "--primary": "oklch(0.205 0 0)",
      "--primary-foreground": "oklch(0.985 0 0)",
      "--secondary": "oklch(0.965 0 0)",
      "--secondary-foreground": "oklch(0.205 0 0)",
      "--muted": "oklch(0.965 0 0)",
      "--muted-foreground": "oklch(0.556 0 0)",
      "--accent": "oklch(0.965 0 0)",
      "--accent-foreground": "oklch(0.205 0 0)",
      "--destructive": "oklch(0.577 0.245 27.325)",
      "--destructive-foreground": "oklch(0.577 0.245 27.325)",
      "--border": "oklch(0.922 0 0)",
      "--input": "oklch(0.922 0 0)",
      "--ring": "oklch(0.708 0 0)",
      "--sidebar-background": "oklch(0.985 0 0)",
      "--sidebar-foreground": "oklch(0.145 0 0)",
      "--sidebar-primary": "oklch(0.205 0 0)",
      "--sidebar-primary-foreground": "oklch(0.985 0 0)",
      "--sidebar-accent": "oklch(0.965 0 0)",
      "--sidebar-accent-foreground": "oklch(0.205 0 0)",
      "--sidebar-border": "oklch(0.922 0 0)",
      "--sidebar-ring": "oklch(0.708 0 0)",
    },
    dark: {
      "--background": "oklch(0.145 0 0)",
      "--foreground": "oklch(0.985 0 0)",
      "--card": "oklch(0.145 0 0)",
      "--card-foreground": "oklch(0.985 0 0)",
      "--popover": "oklch(0.145 0 0)",
      "--popover-foreground": "oklch(0.985 0 0)",
      "--primary": "oklch(0.985 0 0)",
      "--primary-foreground": "oklch(0.205 0 0)",
      "--secondary": "oklch(0.269 0 0)",
      "--secondary-foreground": "oklch(0.985 0 0)",
      "--muted": "oklch(0.269 0 0)",
      "--muted-foreground": "oklch(0.708 0 0)",
      "--accent": "oklch(0.269 0 0)",
      "--accent-foreground": "oklch(0.985 0 0)",
      "--destructive": "oklch(0.396 0.141 25.723)",
      "--destructive-foreground": "oklch(0.637 0.237 25.331)",
      "--border": "oklch(0.269 0 0)",
      "--input": "oklch(0.269 0 0)",
      "--ring": "oklch(0.439 0 0)",
      "--sidebar-background": "oklch(0.205 0 0)",
      "--sidebar-foreground": "oklch(0.985 0 0)",
      "--sidebar-primary": "oklch(0.488 0.243 264.376)",
      "--sidebar-primary-foreground": "oklch(0.985 0 0)",
      "--sidebar-accent": "oklch(0.269 0 0)",
      "--sidebar-accent-foreground": "oklch(0.985 0 0)",
      "--sidebar-border": "oklch(0.269 0 0)",
      "--sidebar-ring": "oklch(0.439 0 0)",
    },
  },
  {
    id: "dark-academia",
    name: "Dark academia",
    light: {
      "--background": "#F8F5EE",
      "--foreground": "#2B1B3D",
      "--card": "#EFEBE2",
      "--card-foreground": "#2B1B3D",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#2B1B3D",
      "--primary": "#8B6914",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#F2E8D0",
      "--secondary-foreground": "#2B1B3D",
      "--muted": "#EFEBE2",
      "--muted-foreground": "#6B5A7A",
      "--accent": "#F2E8D0",
      "--accent-foreground": "#2B1B3D",
      "--destructive": "#B91C1C",
      "--destructive-foreground": "#B91C1C",
      "--border": "#D8D0C4",
      "--input": "#D8D0C4",
      "--ring": "#8B6914",
      "--sidebar-background": "#EFEBE2",
      "--sidebar-foreground": "#2B1B3D",
      "--sidebar-primary": "#8B6914",
      "--sidebar-primary-foreground": "#FFFFFF",
      "--sidebar-accent": "#F2E8D0",
      "--sidebar-accent-foreground": "#2B1B3D",
      "--sidebar-border": "#D8D0C4",
      "--sidebar-ring": "#8B6914",
    },
    dark: {
      "--background": "#1A1A1A",
      "--foreground": "#E8D5A3",
      "--card": "#222222",
      "--card-foreground": "#E8D5A3",
      "--popover": "#2A2A2A",
      "--popover-foreground": "#E8D5A3",
      "--primary": "#C9A84C",
      "--primary-foreground": "#1A1A1A",
      "--secondary": "#2E2518",
      "--secondary-foreground": "#E8D5A3",
      "--muted": "#222222",
      "--muted-foreground": "#998866",
      "--accent": "#2E2518",
      "--accent-foreground": "#E8D5A3",
      "--destructive": "#DC2626",
      "--destructive-foreground": "#FCA5A5",
      "--border": "#3A3A3A",
      "--input": "#3A3A3A",
      "--ring": "#C9A84C",
      "--sidebar-background": "#141414",
      "--sidebar-foreground": "#E8D5A3",
      "--sidebar-primary": "#C9A84C",
      "--sidebar-primary-foreground": "#1A1A1A",
      "--sidebar-accent": "#2E2518",
      "--sidebar-accent-foreground": "#E8D5A3",
      "--sidebar-border": "#3A3530",
      "--sidebar-ring": "#C9A84C",
    },
  },
  {
    id: "modern-mystic",
    name: "Modern mystic",
    light: {
      "--background": "#F0F4F8",
      "--foreground": "#1B2A4A",
      "--card": "#E4EBF2",
      "--card-foreground": "#1B2A4A",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1B2A4A",
      "--primary": "#0097A7",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#DFF5F8",
      "--secondary-foreground": "#1B2A4A",
      "--muted": "#E4EBF2",
      "--muted-foreground": "#4A6280",
      "--accent": "#DFF5F8",
      "--accent-foreground": "#1B2A4A",
      "--destructive": "#B91C1C",
      "--destructive-foreground": "#B91C1C",
      "--border": "#C8D6E0",
      "--input": "#C8D6E0",
      "--ring": "#0097A7",
      "--sidebar-background": "#E4EBF2",
      "--sidebar-foreground": "#1B2A4A",
      "--sidebar-primary": "#0097A7",
      "--sidebar-primary-foreground": "#FFFFFF",
      "--sidebar-accent": "#DFF5F8",
      "--sidebar-accent-foreground": "#1B2A4A",
      "--sidebar-border": "#C8D6E0",
      "--sidebar-ring": "#0097A7",
    },
    dark: {
      "--background": "#0D1B2E",
      "--foreground": "#E0F0F8",
      "--card": "#0F1F33",
      "--card-foreground": "#E0F0F8",
      "--popover": "#152840",
      "--popover-foreground": "#E0F0F8",
      "--primary": "#00BCD4",
      "--primary-foreground": "#0D1B2E",
      "--secondary": "#0A2530",
      "--secondary-foreground": "#E0F0F8",
      "--muted": "#0F1F33",
      "--muted-foreground": "#6A9AB0",
      "--accent": "#0A2530",
      "--accent-foreground": "#E0F0F8",
      "--destructive": "#DC2626",
      "--destructive-foreground": "#FCA5A5",
      "--border": "#1A3348",
      "--input": "#1A3348",
      "--ring": "#00BCD4",
      "--sidebar-background": "#091526",
      "--sidebar-foreground": "#E0F0F8",
      "--sidebar-primary": "#00BCD4",
      "--sidebar-primary-foreground": "#0D1B2E",
      "--sidebar-accent": "#0A2530",
      "--sidebar-accent-foreground": "#E0F0F8",
      "--sidebar-border": "#1A3348",
      "--sidebar-ring": "#00BCD4",
    },
  },
  {
    id: "warm-craft",
    name: "Warm craft",
    light: {
      "--background": "#FBF7EE",
      "--foreground": "#3E2723",
      "--card": "#F0E8D8",
      "--card-foreground": "#3E2723",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#3E2723",
      "--primary": "#B07D10",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#FAF0D8",
      "--secondary-foreground": "#3E2723",
      "--muted": "#F0E8D8",
      "--muted-foreground": "#7D6050",
      "--accent": "#FAF0D8",
      "--accent-foreground": "#3E2723",
      "--destructive": "#B91C1C",
      "--destructive-foreground": "#B91C1C",
      "--border": "#DDD0BC",
      "--input": "#DDD0BC",
      "--ring": "#B07D10",
      "--sidebar-background": "#F0E8D8",
      "--sidebar-foreground": "#3E2723",
      "--sidebar-primary": "#B07D10",
      "--sidebar-primary-foreground": "#FFFFFF",
      "--sidebar-accent": "#FAF0D8",
      "--sidebar-accent-foreground": "#3E2723",
      "--sidebar-border": "#DDD0BC",
      "--sidebar-ring": "#B07D10",
    },
    dark: {
      "--background": "#3E2723",
      "--foreground": "#F5F0E1",
      "--card": "#46302A",
      "--card-foreground": "#F5F0E1",
      "--popover": "#503830",
      "--popover-foreground": "#F5F0E1",
      "--primary": "#D4930D",
      "--primary-foreground": "#1A0800",
      "--secondary": "#4A3020",
      "--secondary-foreground": "#F5F0E1",
      "--muted": "#46302A",
      "--muted-foreground": "#BCA890",
      "--accent": "#4A3020",
      "--accent-foreground": "#F5F0E1",
      "--destructive": "#DC2626",
      "--destructive-foreground": "#FCA5A5",
      "--border": "#5A4035",
      "--input": "#5A4035",
      "--ring": "#D4930D",
      "--sidebar-background": "#33201C",
      "--sidebar-foreground": "#F5F0E1",
      "--sidebar-primary": "#D4930D",
      "--sidebar-primary-foreground": "#1A0800",
      "--sidebar-accent": "#4A3020",
      "--sidebar-accent-foreground": "#F5F0E1",
      "--sidebar-border": "#5A4035",
      "--sidebar-ring": "#D4930D",
    },
  },
];

/** デフォルトのカラーテーマID（colorTheme 未設定時に使用） */
export const DEFAULT_COLOR_THEME = "dark-academia";
