import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { Ajv } from "ajv";
import standaloneCode from "ajv/dist/standalone/index.js";

import { scanBundleV1Schema } from "../src/schema.js";

const GENERATED_FILE_URL = new URL(
  "../src/generated/scanBundleV1Validator.generated.ts",
  import.meta.url,
);

const GENERATED_BANNER = `/* eslint-disable */
// @ts-nocheck
// Generated by scripts/generateScanBundleV1Validator.ts. Do not edit.
`;

const UCS2_LENGTH_REQUIRE =
  /const (func\d+) = require\("ajv\/dist\/runtime\/ucs2length"\)\.default;/g;

const FORBIDDEN_RUNTIME_CODE: ReadonlyArray<{
  label: string;
  pattern: RegExp;
}> = [
  { label: "CommonJS require", pattern: /\brequire\s*\(/u },
  { label: "Function constructor", pattern: /\b(?:new\s+)?Function\s*\(/u },
  { label: "eval", pattern: /\beval\s*\(/u },
];

function inlineUnicodeCodePointLength(source: string): string {
  let replacements = 0;
  const replaced = source.replace(
    UCS2_LENGTH_REQUIRE,
    (_match, functionName: string) => {
      replacements += 1;
      return `const ${functionName} = (value) => {
  let length = 0;
  for (const _codePoint of value) length += 1;
  return length;
};`;
    },
  );

  if (replacements !== 1) {
    throw new Error(
      `Expected exactly one Ajv ucs2length helper, found ${replacements}.`,
    );
  }
  return replaced;
}

export function assertCspSafeValidatorSource(source: string): void {
  for (const forbidden of FORBIDDEN_RUNTIME_CODE) {
    if (forbidden.pattern.test(source)) {
      throw new Error(
        `Generated validator contains forbidden ${forbidden.label}.`,
      );
    }
  }
}

export function generateScanBundleV1ValidatorSource(): string {
  const ajv = new Ajv({
    allErrors: true,
    strict: false,
    code: {
      source: true,
      esm: true,
      lines: true,
    },
  });
  const validate = ajv.compile(scanBundleV1Schema);
  const standaloneSource = standaloneCode(ajv, validate);
  const cspSafeSource = inlineUnicodeCodePointLength(standaloneSource);
  assertCspSafeValidatorSource(cspSafeSource);
  return `${GENERATED_BANNER}${cspSafeSource.trimEnd()}\n`;
}

async function run(): Promise<void> {
  const generatedPath = fileURLToPath(GENERATED_FILE_URL);
  const expected = generateScanBundleV1ValidatorSource();

  if (process.argv.includes("--check")) {
    let actual: string;
    try {
      actual = await readFile(generatedPath, "utf8");
    } catch {
      throw new Error(
        `Generated validator is missing. Run "pnpm --filter @grimodex/scan-contract generate:validator".`,
      );
    }
    if (actual !== expected) {
      throw new Error(
        `Generated validator is stale. Run "pnpm --filter @grimodex/scan-contract generate:validator".`,
      );
    }
    return;
  }

  await mkdir(path.dirname(generatedPath), { recursive: true });
  await writeFile(generatedPath, expected, "utf8");
  process.stdout.write(
    `Generated ${path.relative(process.cwd(), generatedPath)}\n`,
  );
}

const invokedPath = process.argv[1] ? path.resolve(process.argv[1]) : null;
if (
  invokedPath !== null &&
  invokedPath === path.resolve(fileURLToPath(import.meta.url))
) {
  await run();
}
