import {
  memo,
  useState,
  useRef,
  useCallback,
  useEffect,
  useSyncExternalStore,
} from "react";
import { Check, X } from "lucide-react";
import { motion } from "motion/react";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { NodeToolbar, Position, type NodeProps } from "@xyflow/react";
import { FloatingHandle } from "./FloatingHandle";
import { NodeBranchToolbar } from "./NodeBranchToolbar";
import { StickyRichTextBody } from "@/features/sticky/StickyRichTextBody";
import { StickyBodyEditor } from "@/features/sticky/StickyBodyEditor";
import { StickyPaperVisual } from "@/features/sticky/StickyPaperVisual";
import {
  updateSticky,
  extractPreviewText,
  pendingAutoFocusIds,
} from "../mapApi";
import { resolveStickyHex } from "@/lib/stickyPalettes";
import { DURATIONS, EASINGS, useReducedMotion } from "@/lib/animation";
import { rootCause } from "@/lib/debugLog";
import { registerQuiescenceParticipant } from "@/application/lifecycle/quiescenceParticipants";
import {
  canScheduleQuiescenceMutation,
  isQuiescenceLeaseActive,
  subscribeQuiescenceLease,
} from "@/application/lifecycle/quiescenceLease";
import {
  ContextMenu,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuTrigger,
} from "@/components/ui/context-menu";
import {
  createStickyDraftController,
  type StickyDraftController,
} from "@/features/sticky/stickyDraftController";

export interface StickyNodeData {
  id: string;
  title: string;
  body: string;
  previewText: string;
  paletteId: string;
  colorSlot: number;
  colorBy?: string;
  rotation?: number;
  isDeleting?: boolean;
  /** true when the sticky was generated by AI (map_stickies.ai_derived).
   *  Drives the onCopy provenance label. Survives adoption (Plan B): an adopted
   *  sticky keeps aiDerived=true even though it is no longer branch-attached. */
  aiDerived?: boolean;
  /** true while the sticky still belongs to an AI Branch
   *  (map_stickies.ai_branch_id !== null). Adoption clears this; only
   *  branch-attached stickies show the adopt/reject affordance. */
  branchAttached?: boolean;
  /** 採用: branch から切り離して通常 Sticky 化する。 */
  onAdopt?: () => void;
  /** 不採用: Sticky をゴミ箱へ送る (削除アニメーション経由)。 */
  onReject?: () => void;
  onExitComplete?: (id: string) => void;
  onUpdate?: (updates: {
    title?: string;
    body?: string;
    previewText?: string;
    paletteId?: string;
    colorSlot?: number;
  }) => Promise<void>;
  onBranchFrom?: (dir: "left" | "right") => void;
  [key: string]: unknown;
}

const STICKY_ANIMATE = {
  opacity: 1,
  y: 0,
  rotateX: 0,
  transition: { duration: DURATIONS.slow, ease: EASINGS.easeOut },
} as const;

const STICKY_EXIT = {
  opacity: 0,
  y: -100,
  rotate: -16,
  transition: { duration: DURATIONS.slow, ease: EASINGS.easeOut },
} as const;

const STICKY_ENTER_VARIANTS = {
  initial: { opacity: 0, y: -14, rotateX: -24 },
  animate: STICKY_ANIMATE,
  exit: STICKY_EXIT,
} as const;

const STICKY_REDUCED_VARIANTS = {
  initial: { opacity: 1, y: 0, rotateX: 0 },
  animate: STICKY_ANIMATE,
  exit: STICKY_EXIT,
} as const;

export const StickyNode = memo(function StickyNode({
  data,
  selected,
  isConnectable,
}: NodeProps) {
  const { t } = useTranslation();
  const d = data as StickyNodeData;
  const rotation = d.rotation ?? 0;
  const isDeleting = d.isDeleting ?? false;
  const reducedMotion = useReducedMotion();
  const enterVariants = reducedMotion
    ? STICKY_REDUCED_VARIANTS
    : STICKY_ENTER_VARIANTS;
  const exitFiredRef = useRef(false);

  const [editing, setEditing] = useState(false);
  const [deletePersistenceReady, setDeletePersistenceReady] = useState(false);
  const [hovered, setHovered] = useState(false);
  const [focusWithin, setFocusWithin] = useState(false);
  const [glueOrient, setGlueOrient] = useState<"left" | "top">("left");
  const quiescenceLeaseActive = useSyncExternalStore(
    subscribeQuiescenceLease,
    isQuiescenceLeaseActive,
    () => false,
  );
  const draftControllerRef = useRef<StickyDraftController | null>(null);
  if (
    draftControllerRef.current === null ||
    draftControllerRef.current.id !== d.id
  ) {
    draftControllerRef.current = createStickyDraftController(d.id, d.body);
  }
  const draftController = draftControllerRef.current;
  draftController.setPersist((body) => {
    const updates = { body, previewText: extractPreviewText(body) };
    return d.onUpdate
      ? d.onUpdate(updates)
      : updateSticky(d.id, updates).then(() => undefined);
  });
  const measureRef = useRef<HTMLDivElement>(null);
  const wrapperElRef = useRef<HTMLDivElement>(null);
  const mountedRef = useRef(false);
  const isDeletingRef = useRef(isDeleting);
  isDeletingRef.current = isDeleting;

  // Sync body from parent when not editing
  useEffect(() => {
    if (!editing && !draftController.dirty) {
      draftController.latestBody = d.body;
    }
  }, [d.body, draftController, editing]);

  useEffect(() => {
    mountedRef.current = true;
    return () => {
      mountedRef.current = false;
    };
  }, []);

  // Auto-enter edit mode for newly created stickies (branch / add)
  useEffect(() => {
    if (quiescenceLeaseActive) return;
    if (pendingAutoFocusIds.has(d.id)) {
      pendingAutoFocusIds.delete(d.id);
      setEditing(true);
    }
  }, [d.id, quiescenceLeaseActive]);

  // ResizeObserver: switch glue side based on content height with hysteresis
  // left→top at >= 110px, top→left at <= 90px (dead band avoids oscillation)
  useEffect(() => {
    const el = measureRef.current;
    if (!el) return;
    const ro = new ResizeObserver(([entry]) => {
      const h = entry.contentRect.height;
      setGlueOrient((prev) => {
        if (prev === "left" && h >= 110) return "top";
        if (prev === "top" && h <= 90) return "left";
        return prev;
      });
    });
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  useEffect(() => {
    let mounted = true;
    let unregister = () => {};
    const participant = {
      id: `sticky:${draftController.id}`,
      flush: async () => {
        await draftController.save();
        if (!mounted && !draftController.dirty) unregister();
      },
      discard: () => {
        draftController.discard();
        if (!mounted) unregister();
      },
      recovery: () =>
        draftController.dirty
          ? {
              kind: "map-sticky",
              id: draftController.id,
              prosemirror: draftController.latestBody,
            }
          : null,
    };
    unregister = registerQuiescenceParticipant(participant);

    return () => {
      mounted = false;
      if (!draftController.dirty) {
        unregister();
        return;
      }
      // Do not retire the participant until persistence succeeds. A failed
      // background flush keeps both its detached save closure and recovery
      // snapshot available to the next lifecycle retry.
      void participant.flush().catch(() => {
        // Background cleanup must terminate its rejection. The participant
        // remains registered, so strict quiescence can retry or discard it.
      });
    };
  }, [draftController]);

  const finishEditingRef = useRef<Promise<boolean> | null>(null);
  const exitEditing = useCallback((): Promise<boolean> => {
    if (finishEditingRef.current) return finishEditingRef.current;

    const pending = draftController
      .save()
      .then(() => {
        finishEditingRef.current = null;
        if (mountedRef.current) {
          setEditing(false);
          if (isDeletingRef.current) setDeletePersistenceReady(true);
        }
        return true;
      })
      .catch((error: unknown) => {
        finishEditingRef.current = null;
        if (mountedRef.current) {
          toast.error(t("autoSave.failed", { reason: rootCause(error) }));
        }
        // Keep the editor and dirty controller alive for Escape/click-away,
        // lifecycle retry, or recovery export. User event callers intentionally
        // fire-and-forget this promise, so the rejection must end here.
        return false;
      });
    finishEditingRef.current = pending;
    return pending;
  }, [draftController, t]);

  // 削除トリガー (isDeleting=true) が立ったら、編集中の未保存内容を即保存する。
  // 永続化が成功するまでは exit animation / delete completion を開始しない。
  useEffect(() => {
    if (!isDeleting) {
      exitFiredRef.current = false;
      setDeletePersistenceReady(false);
      return;
    }
    void exitEditing();
  }, [exitEditing, isDeleting]);

  // Click-away: document-level pointerdown 監視。React Flow が pane に
  // transform をかけているため `position: fixed` + `zIndex: -1` の
  // sentinel div ではクリックを拾えない。
  useEffect(() => {
    if (!editing) return;
    const handler = (e: PointerEvent) => {
      const root = wrapperElRef.current;
      if (root && !root.contains(e.target as Node)) {
        void exitEditing();
      }
    };
    document.addEventListener("pointerdown", handler, true);
    return () => document.removeEventListener("pointerdown", handler, true);
  }, [editing, exitEditing]);

  const showAdoptUI =
    (d.branchAttached ?? false) &&
    !editing &&
    !isDeleting &&
    !quiescenceLeaseActive;

  return (
    <ContextMenu>
      <ContextMenuTrigger asChild>
        <div
          ref={wrapperElRef}
          style={{ position: "relative" }}
          aria-disabled={quiescenceLeaseActive || undefined}
          data-quiescence-locked={quiescenceLeaseActive || undefined}
          onMouseEnter={() => setHovered(true)}
          onMouseLeave={() => setHovered(false)}
          onContextMenu={(event) => {
            // MapCanvas already owns the general node context menu on the
            // enclosing ReactFlow node. A branch-attached Sticky exposes its
            // dedicated Adopt/Reject menu here, so do not let the same native
            // contextmenu event open both Radix menus. Normal/adopted Stickies
            // have no local menu and must keep bubbling to MapCanvas.
            if (showAdoptUI) event.stopPropagation();
          }}
          onFocusCapture={() => setFocusWithin(true)}
          onBlurCapture={(event) => {
            if (
              !event.currentTarget.contains(event.relatedTarget as Node | null)
            ) {
              setFocusWithin(false);
            }
          }}
        >
          <FloatingHandle isConnectable={isConnectable} />
          <NodeBranchToolbar
            onBranchFrom={quiescenceLeaseActive ? undefined : d.onBranchFrom}
          />

          {/* AI Branch 由来 Sticky の採用 / 不採用。branch 在籍中かつ hover 時のみ。
          採用 = branch から切り離して通常 Sticky 化 (provenance は保持)。
          不採用 = ゴミ箱へ (既存の削除アニメーション経由)。 */}
          {showAdoptUI && (
            <NodeToolbar
              position={Position.Top}
              offset={6}
              isVisible={hovered || focusWithin || selected}
              className="map-sticky-adopt-toolbar"
            >
              <button
                type="button"
                aria-label={t("map.sticky.adoptAriaLabel")}
                title={t("map.sticky.adoptTitle")}
                onClick={(e) => {
                  e.stopPropagation();
                  d.onAdopt?.();
                }}
                className="map-sticky-adopt-btn"
              >
                <Check size={11} strokeWidth={3} aria-hidden />
                {t("map.sticky.adopt")}
              </button>
              <button
                type="button"
                aria-label={t("map.sticky.rejectAriaLabel")}
                title={t("map.sticky.rejectTitle")}
                onClick={(e) => {
                  e.stopPropagation();
                  d.onReject?.();
                }}
                className="map-sticky-reject-btn"
              >
                <X size={11} aria-hidden />
                {t("map.sticky.reject")}
              </button>
            </NodeToolbar>
          )}

          {/* motion wrapper: enter/exit animation. transformOrigin switches on delete. */}
          <motion.div
            data-testid="sticky-motion"
            initial={enterVariants.initial}
            animate={
              isDeleting && deletePersistenceReady
                ? enterVariants.exit
                : enterVariants.animate
            }
            style={{ transformOrigin: isDeleting ? "100% 100%" : "50% 0%" }}
            onAnimationComplete={() => {
              if (
                isDeleting &&
                deletePersistenceReady &&
                !exitFiredRef.current
              ) {
                exitFiredRef.current = true;
                d.onExitComplete?.(d.id);
              }
            }}
          >
            {/* sticky-paper-wrap: carries rotation. */}
            <div
              data-testid="sticky-paper-wrap"
              style={{
                position: "relative",
                transform: `rotate(${rotation}deg)`,
              }}
            >
              <StickyPaperVisual
                data-testid="sticky-paper"
                data-glue={glueOrient}
                paperColor={resolveStickyHex(d.paletteId, d.colorSlot)}
                style={{
                  width: 200,
                  minHeight: 52,
                  maxHeight: editing ? 480 : undefined,
                  overflow: editing ? "auto" : "visible",
                  outline: selected ? "2px solid #534AB7" : "none",
                  outlineOffset: "2px",
                  cursor: editing ? "text" : "default",
                  userSelect: editing ? "text" : "none",
                }}
                onDoubleClick={(e) => {
                  if (
                    !editing &&
                    !isDeleting &&
                    canScheduleQuiescenceMutation()
                  ) {
                    e.stopPropagation();
                    setEditing(true);
                  }
                }}
              >
                {/* Content area measured by ResizeObserver。
                コピーの provenance は ProseMirror ネイティブの copy serialization に
                委譲する。AI Branch 由来 Sticky の本文は作成時に "ai" authorship mark
                をシード済みで、人間が編集した範囲は AiEditedPlugin が mark を剥がす
                ため、PM が出力する span[data-authorship] が per-span の source を
                正しく載せる (EditorPane handlePaste Case 2 → parseClipboardHtml が
                拾う)。一律 source でスタンプしていた旧 onCopy だと AI Sticky の
                人間編集部分まで "ai" になっていた (本 fix の対象)。非編集時は
                userSelect:none で選択不可なのでコピー自体が発生しない。 */}
                <div
                  ref={measureRef}
                  data-testid="sticky-content"
                  className="sticky-content"
                >
                  {/* Body */}
                  {editing ? (
                    <StickyBodyEditor
                      body={
                        draftController.dirty
                          ? draftController.latestBody
                          : d.body
                      }
                      onContentChange={(json) => {
                        if (!canScheduleQuiescenceMutation()) return;
                        draftController.markDirty(json);
                      }}
                      onEscape={exitEditing}
                      trashOrigin={{ kind: "sticky", id: d.id }}
                      enableAiEdited
                      className="nodrag nowheel nopan"
                      style={{ fontSize: 12, lineHeight: 1.5 }}
                      onPointerDown={(event) => event.stopPropagation()}
                    />
                  ) : (
                    <StickyRichTextBody body={d.body} />
                  )}
                </div>
              </StickyPaperVisual>
            </div>
          </motion.div>
        </div>
      </ContextMenuTrigger>
      {showAdoptUI && (
        <ContextMenuContent>
          <ContextMenuItem onSelect={() => d.onAdopt?.()}>
            <Check size={13} aria-hidden />
            {t("map.sticky.adopt")}
          </ContextMenuItem>
          <ContextMenuItem
            onSelect={() => d.onReject?.()}
            className="text-destructive focus:text-destructive"
          >
            <X size={13} aria-hidden />
            {t("map.sticky.reject")}
          </ContextMenuItem>
        </ContextMenuContent>
      )}
    </ContextMenu>
  );
});
