import {
  memo,
  useState,
  useRef,
  useCallback,
  useEffect,
  useMemo,
  type CSSProperties,
} from "react";
import { motion } from "motion/react";
import { NodeToolbar, Position, type NodeProps } from "@xyflow/react";
import { FloatingHandle } from "./FloatingHandle";
import { NodeBranchToolbar } from "./NodeBranchToolbar";
import { useEditor, EditorContent } from "@tiptap/react";
import { generateHTML } from "@tiptap/core";
import { getStickyEditorExtensions } from "@/features/editor/extensions";
import { useTrashBinCapture } from "@/features/editor/useTrashBinCapture";
import {
  updateSticky,
  extractPreviewText,
  pendingAutoFocusIds,
} from "../mapApi";
import { resolveStickyHex } from "@/lib/stickyPalettes";
import {
  aiEditedKey,
  createAiEditedPlugin,
} from "@/features/attribution/AiEditedPlugin";
import { isEditorViewReady } from "@/features/editor/isEditorViewReady";
import { DURATIONS, EASINGS, useReducedMotion } from "@/lib/animation";

export interface StickyNodeData {
  id: string;
  title: string;
  body: string;
  previewText: string;
  paletteId: string;
  colorSlot: number;
  colorBy?: string;
  rotation?: number;
  isDeleting?: boolean;
  /** true when the sticky was generated by AI (map_stickies.ai_derived).
   *  Drives the onCopy provenance label. Survives adoption (Plan B): an adopted
   *  sticky keeps aiDerived=true even though it is no longer branch-attached. */
  aiDerived?: boolean;
  /** true while the sticky still belongs to an AI Branch
   *  (map_stickies.ai_branch_id !== null). Adoption clears this; only
   *  branch-attached stickies show the adopt/reject affordance. */
  branchAttached?: boolean;
  /** 採用: branch から切り離して通常 Sticky 化する。 */
  onAdopt?: () => void;
  /** 不採用: Sticky をゴミ箱へ送る (削除アニメーション経由)。 */
  onReject?: () => void;
  onExitComplete?: (id: string) => void;
  onUpdate?: (updates: {
    title?: string;
    body?: string;
    previewText?: string;
    paletteId?: string;
    colorSlot?: number;
  }) => Promise<void>;
  onBranchFrom?: (dir: "left" | "right") => void;
  [key: string]: unknown;
}

const STICKY_ANIMATE = {
  opacity: 1,
  y: 0,
  rotateX: 0,
  transition: { duration: DURATIONS.slow, ease: EASINGS.easeOut },
} as const;

const STICKY_EXIT = {
  opacity: 0,
  y: -100,
  rotate: -16,
  transition: { duration: DURATIONS.slow, ease: EASINGS.easeOut },
} as const;

const STICKY_ENTER_VARIANTS = {
  initial: { opacity: 0, y: -14, rotateX: -24 },
  animate: STICKY_ANIMATE,
  exit: STICKY_EXIT,
} as const;

const STICKY_REDUCED_VARIANTS = {
  initial: { opacity: 1, y: 0, rotateX: 0 },
  animate: STICKY_ANIMATE,
  exit: STICKY_EXIT,
} as const;

function parseBodyContent(body: string): object | undefined {
  if (!body) return undefined;
  try {
    return JSON.parse(body);
  } catch {
    return undefined;
  }
}

function StickyBodyView({ body }: { body: string }) {
  const html = useMemo(() => {
    const json = parseBodyContent(body);
    if (!json) return "";
    try {
      return generateHTML(json, getStickyEditorExtensions());
    } catch {
      return "";
    }
  }, [body]);
  return (
    <div
      data-testid="sticky-body-view"
      className="sticky-body-view"
      style={{
        fontSize: 12,
        lineHeight: 1.5,
        color: "rgba(0,0,0,0.65)",
        wordBreak: "break-word",
      }}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

interface StickyBodyEditorProps {
  stickyId: string;
  body: string;
  onContentChange: (json: string) => void;
  onEscape: () => void;
}

function StickyBodyEditor({
  stickyId,
  body,
  onContentChange,
  onEscape,
}: StickyBodyEditorProps) {
  const editor = useEditor({
    extensions: getStickyEditorExtensions(),
    content: parseBodyContent(body),
    onUpdate({ editor: ed }) {
      onContentChange(JSON.stringify(ed.getJSON()));
    },
  });
  useTrashBinCapture(editor, { kind: "sticky", id: stickyId });

  // Register AiEditedPlugin so text the human types inside an AI-seeded span
  // loses its "ai" authorship mark (becomes human). This is what lets copy
  // distinguish edited (human) text from AI-original text within one sticky.
  // We register only this plugin (not the full useAttribution) to keep the
  // sticky's visual behavior unchanged — no attribution decorations.
  useEffect(() => {
    if (!isEditorViewReady(editor)) return;
    const has = editor.view.state.plugins.find(
      (p) => p.spec.key === aiEditedKey,
    );
    if (!has) editor.registerPlugin(createAiEditedPlugin());
    return () => {
      if (isEditorViewReady(editor)) editor.unregisterPlugin(aiEditedKey);
    };
  }, [editor]);

  useEffect(() => {
    if (editor) {
      setTimeout(() => editor.commands.focus("end"), 0);
    }
  }, [editor]);

  if (!editor) return null;

  return (
    // `nodrag`: xyflow's d3-drag captures pointerdown on the node and
    // preventDefault()s it, which blocks caret placement in the contenteditable.
    // The class makes the drag filter skip this region so clicks move the caret.
    // (React onPointerDown stopPropagation runs at the React root, after d3-drag's
    // element-level native listener already fired — too late.) `nowheel`/`nopan`
    // let the editor scroll/select without zooming or panning the map. Same
    // pattern as UserEdge's editable label.
    <div
      onPointerDown={(e) => e.stopPropagation()}
      onKeyDown={(e) => {
        if (e.key === "Escape") {
          e.preventDefault();
          e.stopPropagation();
          onEscape();
        }
      }}
      style={{ fontSize: 12, lineHeight: 1.5 }}
      className="sticky-editor nodrag nowheel nopan"
    >
      <EditorContent editor={editor} />
    </div>
  );
}

export const StickyNode = memo(function StickyNode({
  data,
  selected,
  isConnectable,
}: NodeProps) {
  const d = data as StickyNodeData;
  const rotation = d.rotation ?? 0;
  const isDeleting = d.isDeleting ?? false;
  const reducedMotion = useReducedMotion();
  const enterVariants = reducedMotion
    ? STICKY_REDUCED_VARIANTS
    : STICKY_ENTER_VARIANTS;
  const exitFiredRef = useRef(false);

  const [editing, setEditing] = useState(false);
  const [hovered, setHovered] = useState(false);
  const [glueOrient, setGlueOrient] = useState<"left" | "top">("left");
  const latestBodyRef = useRef<string>(d.body);
  const measureRef = useRef<HTMLDivElement>(null);
  const wrapperElRef = useRef<HTMLDivElement>(null);

  // Sync body from parent when not editing
  useEffect(() => {
    if (!editing) {
      latestBodyRef.current = d.body;
    }
  }, [d.body, editing]);

  // Auto-enter edit mode for newly created stickies (branch / add)
  useEffect(() => {
    if (pendingAutoFocusIds.has(d.id)) {
      pendingAutoFocusIds.delete(d.id);
      setEditing(true);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // ResizeObserver: switch glue side based on content height with hysteresis
  // left→top at >= 110px, top→left at <= 90px (dead band avoids oscillation)
  useEffect(() => {
    const el = measureRef.current;
    if (!el) return;
    const ro = new ResizeObserver(([entry]) => {
      const h = entry.contentRect.height;
      setGlueOrient((prev) => {
        if (prev === "left" && h >= 110) return "top";
        if (prev === "top" && h <= 90) return "left";
        return prev;
      });
    });
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  const save = useCallback(async () => {
    const json = latestBodyRef.current;
    const preview = extractPreviewText(json);
    await (d.onUpdate?.({ body: json, previewText: preview }) ??
      updateSticky(d.id, { body: json, previewText: preview }));
  }, [d]);

  const exitEditing = useCallback(async () => {
    setEditing(false);
    await save();
  }, [save]);

  // 削除トリガー (isDeleting=true) が立ったら、編集中の未保存内容を即保存する。
  // exitEditing 経由でないと save が走らないため、Undo で復元する内容に
  // ユーザーが編集中だった文字が反映されないバグの根本対応。
  useEffect(() => {
    if (isDeleting && editing) {
      void save();
      setEditing(false);
    }
  }, [isDeleting, editing, save]);

  // Click-away: document-level pointerdown 監視。React Flow が pane に
  // transform をかけているため `position: fixed` + `zIndex: -1` の
  // sentinel div ではクリックを拾えない。
  useEffect(() => {
    if (!editing) return;
    const handler = (e: PointerEvent) => {
      const root = wrapperElRef.current;
      if (root && !root.contains(e.target as Node)) {
        void exitEditing();
      }
    };
    document.addEventListener("pointerdown", handler, true);
    return () => document.removeEventListener("pointerdown", handler, true);
  }, [editing, exitEditing]);

  // Unmount safety net: パネル切替 / ボード切替 / アプリ終了などで
  // StickyNode が unmount された際、編集中なら最新本文を flush する。
  const editingRef = useRef(editing);
  const saveRef = useRef(save);
  useEffect(() => {
    editingRef.current = editing;
    saveRef.current = save;
  });
  useEffect(() => {
    return () => {
      if (editingRef.current) {
        void saveRef.current();
      }
    };
  }, []);

  const showAdoptUI = (d.branchAttached ?? false) && !editing;

  return (
    <div
      ref={wrapperElRef}
      style={{ position: "relative" }}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
    >
      <FloatingHandle isConnectable={isConnectable} />
      <NodeBranchToolbar onBranchFrom={d.onBranchFrom} />

      {/* AI Branch 由来 Sticky の採用 / 不採用。branch 在籍中かつ hover 時のみ。
          採用 = branch から切り離して通常 Sticky 化 (provenance は保持)。
          不採用 = ゴミ箱へ (既存の削除アニメーション経由)。 */}
      {showAdoptUI && (
        <NodeToolbar
          position={Position.Top}
          offset={6}
          isVisible={hovered}
          className="map-sticky-adopt-toolbar"
        >
          <button
            type="button"
            aria-label="この付箋を採用"
            title="採用 (branch から切り離す)"
            onClick={(e) => {
              e.stopPropagation();
              d.onAdopt?.();
            }}
            className="map-sticky-adopt-btn"
          >
            ✓ 採用
          </button>
          <button
            type="button"
            aria-label="この付箋を不採用"
            title="不採用 (ゴミ箱へ)"
            onClick={(e) => {
              e.stopPropagation();
              d.onReject?.();
            }}
            className="map-sticky-reject-btn"
          >
            ✕ 不採用
          </button>
        </NodeToolbar>
      )}

      {/* motion wrapper: enter/exit animation. transformOrigin switches on delete. */}
      <motion.div
        data-testid="sticky-motion"
        initial={enterVariants.initial}
        animate={isDeleting ? enterVariants.exit : enterVariants.animate}
        style={{ transformOrigin: isDeleting ? "100% 100%" : "50% 0%" }}
        onAnimationComplete={() => {
          if (isDeleting && !exitFiredRef.current) {
            exitFiredRef.current = true;
            d.onExitComplete?.(d.id);
          }
        }}
      >
        {/* sticky-paper-wrap: carries rotation. */}
        <div
          data-testid="sticky-paper-wrap"
          style={{ position: "relative", transform: `rotate(${rotation}deg)` }}
        >
          <div
            data-testid="sticky-paper"
            className="sticky-paper"
            data-glue={glueOrient}
            style={
              {
                width: 200,
                minHeight: 52,
                maxHeight: editing ? 480 : undefined,
                overflow: editing ? "auto" : "visible",
                outline: selected ? "2px solid #534AB7" : "none",
                outlineOffset: "2px",
                cursor: editing ? "text" : "default",
                userSelect: editing ? "text" : "none",
                "--sticky-bg-light": resolveStickyHex(d.paletteId, d.colorSlot),
              } as CSSProperties
            }
            onDoubleClick={(e) => {
              if (!editing) {
                e.stopPropagation();
                setEditing(true);
              }
            }}
          >
            {/* Content area measured by ResizeObserver。
                コピーの provenance は ProseMirror ネイティブの copy serialization に
                委譲する。AI Branch 由来 Sticky の本文は作成時に "ai" authorship mark
                をシード済みで、人間が編集した範囲は AiEditedPlugin が mark を剥がす
                ため、PM が出力する span[data-authorship] が per-span の source を
                正しく載せる (EditorPane handlePaste Case 2 → parseClipboardHtml が
                拾う)。一律 source でスタンプしていた旧 onCopy だと AI Sticky の
                人間編集部分まで "ai" になっていた (本 fix の対象)。非編集時は
                userSelect:none で選択不可なのでコピー自体が発生しない。 */}
            <div
              ref={measureRef}
              data-testid="sticky-content"
              className="sticky-content"
            >
              {/* Body */}
              {editing ? (
                <StickyBodyEditor
                  stickyId={d.id}
                  body={d.body}
                  onContentChange={(json) => {
                    latestBodyRef.current = json;
                  }}
                  onEscape={exitEditing}
                />
              ) : (
                <StickyBodyView body={d.body} />
              )}
            </div>
          </div>
        </div>
      </motion.div>
    </div>
  );
});
